import behavioral_social_sciences_aspects_mathematics_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace behavioral_social_sciences_aspects_mathematics_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end behavioral_social_sciences_aspects_mathematics_theorem_canonical_lane_mathlib
end HautevilleHouse
